// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxV5WXqeZWbCuh55ecvXVFxQoYa3VC_aM',
    appId: '1:320828749843:web:81a4f7856c46195767a7e6',
    messagingSenderId: '320828749843',
    projectId: 'chatapp-37174',
    authDomain: 'chatapp-37174.firebaseapp.com',
    storageBucket: 'chatapp-37174.appspot.com',
    measurementId: 'G-R54H6SR8E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_yLvkkF9WpcPKMJ_lj8wwLokI9_3a72Q',
    appId: '1:320828749843:android:f325c134f24bab7367a7e6',
    messagingSenderId: '320828749843',
    projectId: 'chatapp-37174',
    storageBucket: 'chatapp-37174.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACfFOigRQ4afDh4DtPLTzipYR5397ui6I',
    appId: '1:320828749843:ios:47671a180ec1c79c67a7e6',
    messagingSenderId: '320828749843',
    projectId: 'chatapp-37174',
    storageBucket: 'chatapp-37174.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACfFOigRQ4afDh4DtPLTzipYR5397ui6I',
    appId: '1:320828749843:ios:0c9983a30617c3cf67a7e6',
    messagingSenderId: '320828749843',
    projectId: 'chatapp-37174',
    storageBucket: 'chatapp-37174.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
